---
name: "registry"

blobstores:
  - name: images

secrets:
  - name: github

runtimes:
  - name: main
    routes:
      - prefix: "/registry/v1/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081
      - prefix: "/trigger/v1/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081
      - prefix: "/gopkg/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081

    subscriptions:
      - name: "webhook-github"
        envName: "publicweb"
        port: 8080

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: registry
            registry: ghcr.io/pentops
        mountDockerSocket: true
        command: [serve]
        envVars:
          - name: SNS_PREFIX
            fromEnv:
              name: sns-prefix
          - name: SOURCE_REPOS
            fromEnv:
              name: j5-repos

          - name: GRPC_PORT
            value: "8080"

          - name: HTTP_PORT
            value: "8081"

          - name: REGISTRY_STORAGE
            blobstore:
              name: images
              s3_direct: true
          - name: GH_PRIVATE_KEY
            secret:
              secretName: github
              jsonKey: privateKey
          - name: GH_APP_ID
            secret:
              secretName: github
              jsonKey: appId
          - name: GH_INSTALLATION_ID
            secret:
              secretName: github
              jsonKey: installationId
