---
name: "registry"

blobstores:
  - name: images

secrets:
  - name: github

databases:
  - name: main
    postgres:
      runOutbox: true
      dbName: o5
      serverGroup: default
      dbExtensions:
        - "uuid-ossp"

      migrateContainer:
        image:
          name: registry
          registry: ghcr.io/pentops
        command: [migrate]
        envVars:
          - name: "POSTGRES_URL"
            database:
              databaseName: main

runtimes:
  - name: main
    routes:
      - prefix: "/registry/v1/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081
      - prefix: "/trigger/v1/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081
      - prefix: "/gopkg/"
        protocol: ROUTE_PROTOCOL_HTTP
        bypass_ingress: true
        port: 8081
      - prefix: "/registry/github/v1/"
        protocol: ROUTE_PROTOCOL_GRPC
        port: 8080

    subscriptions:
      - name: "/o5.registry.github.v1.WebhookTopic"
        port: 8080
      - name: "/o5.registry.builder.v1.topic.BuilderTopic"
        port: 8080

    containers:
      - name: main
        demand: DEMAND_LIGHT
        image:
            name: registry
            registry: ghcr.io/pentops
        mountDockerSocket: true
        command: [serve]
        envVars:
          - name: POSTGRES_URL
            database:
              databaseName: main

          - name: GRPC_PORT
            value: "8080"

          - name: HTTP_PORT
            value: "8081"

          - name: REGISTRY_STORAGE
            blobstore:
              name: images
              s3_direct: true
          - name: GH_PRIVATE_KEY
            secret:
              secretName: github
              jsonKey: privateKey
          - name: GH_APP_ID
            secret:
              secretName: github
              jsonKey: appId
          - name: GH_INSTALLATION_ID
            secret:
              secretName: github
              jsonKey: installationId
